Add cargo-features resolver
Attempting to run `cargo udeps` throws the following warning:

```
cargo +nightly udeps
error: failed to parse manifest at `/home/tobin/build/github.com/tcharding/nalgebra/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

This can be resolved by adding `cargo-features = ["resolver"]` to the
manifest file as suggested.

_Why_ this is needed by cargo udeps when it is the default behaviour now
I do not know.