Fix rustdoc warnings (#1511)
* CHANGELOG: applied `markdownlint` suggestions

* rustdoc: fixed warnings by `cargo doc --workspace --no-deps --document-private-items`

* BEWARE: fixed a warning, but we won't know if it works before it is published on `docs.rs`.

* CI: upgrade rustc from 1.79 to 1.81 due to
```
error: rustc 1.79.0 is not supported by the following package:
  half@2.6.0 requires rustc 1.81
```

updated snapshot test
ci: snapshot test again, by

```shell
TRYBUILD=overwrite cargo +1.81 test stack
```

---------

Co-authored-by: Alex H. Room <69592136+alexhroom@users.noreply.github.com>