fix flaky in test rotation_between_is_identity (#1542)
This fixes following test failure:

	---- geometry::rotation::proptest_tests::rotation_between_is_identity stdout ----
	proptest: Saving this and future failures in /home/im/projects/patches/nalgebra/proptest-regressions/geometry/rotation.txt
	proptest: If this test was run on a CI system, you may wish to add the following line to your copy of the file. (You may need to create it.)
	cc 3f8e4df3b22ad80e431c610aec6ed6368da0198877fc96a07dd00978cfce619a

	thread 'geometry::rotation::proptest_tests::rotation_between_is_identity' panicked at tests/geometry/rotation.rs:99:5:
	Test failed: assertion failed: `(left == right)`
	  left: `[[1.0, 8.23149217580028e-11, 1.6462984785248345e-10], [-8.231492522718508e-11, 0.9999999999999998, 2.1072620414097273e-8], [-1.6462984611789232e-10, -2.1072620414110825e-8, 0.9999999999999998]]`,
	 right: `[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]` at tests/geometry/rotation.rs:209.
	minimal failing input: v2 = [
		[
			0.0,
			0.0,
		],
	], v3 = [
		[
			0.909512349774636,
			59.888745019601366,
			-71.4865423250859,
		],
	]
		successes: 22
		local rejects: 0
		global rejects: 0