fix: Use reproducible_dmatrix() for Cholesky benches
Random matrices may be not positive-definite and Cholesky decomposition
benchmarks panic because of that:

	Benchmarking cholesky_decompose_unpack_100x100: Warming up for 3.0000 s
	thread 'main' panicked at benches/linalg/cholesky.rs:38:45:
	called `Option::unwrap()` on a `None` value